version: '2'
services:
  mysql-dev:
    restart: always
    build:
      context: https://github.com/CatalpaFlat/docker-mysql/blob/master/Dockerfile
    container_name: mysql-dev
    volumes:
      - /home/catalpaflat/data/mysql-dev:/var/lib/mysql
    ports:
      - 3306:3306
  mysql-stage:
    restart: always
    build:
      context: https://github.com/CatalpaFlat/docker-mysql/blob/master/Dockerfile
    container_name: mysql-stage
    volumes:
      - /home/catalpaflat/data/mysql-stage:/var/lib/mysql
    ports:
      - 3307:3306
  mysql-prod:
    restart: always
    build:
      context: https://github.com/CatalpaFlat/docker-mysql/blob/master/Dockerfile
    container_name: mysql-prod
    volumes:
      - /home/catalpaflat/data/mysql-prod:/var/lib/mysql
    ports:
      - 3308:3306
